/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BlockVin2ScriptSig : The script signature

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BlockVin2ScriptSig {
}

impl BlockVin2ScriptSig {
  /// The script signature
  pub fn new() -> BlockVin2ScriptSig {
    BlockVin2ScriptSig {
    }
  }

}



