/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BlockVin3Prevout : Detailed previous output

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BlockVin3Prevout {
}

impl BlockVin3Prevout {
  /// Detailed previous output
  pub fn new() -> BlockVin3Prevout {
    BlockVin3Prevout {
    }
  }

}



