/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DecodedPsbtInputFinalScriptsig : The final script sig

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DecodedPsbtInputFinalScriptsig {
}

impl DecodedPsbtInputFinalScriptsig {
  /// The final script sig
  pub fn new() -> DecodedPsbtInputFinalScriptsig {
    DecodedPsbtInputFinalScriptsig {
    }
  }

}



