/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DecodedPsbtInputWitnessUtxo : Transaction output for witness UTXOs

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DecodedPsbtInputWitnessUtxo {
}

impl DecodedPsbtInputWitnessUtxo {
  /// Transaction output for witness UTXOs
  pub fn new() -> DecodedPsbtInputWitnessUtxo {
    DecodedPsbtInputWitnessUtxo {
    }
  }

}



