/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DecodedPsbtInputWitnessScript : The witness script

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DecodedPsbtInputWitnessScript {
}

impl DecodedPsbtInputWitnessScript {
  /// The witness script
  pub fn new() -> DecodedPsbtInputWitnessScript {
    DecodedPsbtInputWitnessScript {
    }
  }

}



