/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DecodedScriptSegwit : Witness script details

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DecodedScriptSegwit {
}

impl DecodedScriptSegwit {
  /// Witness script details
  pub fn new() -> DecodedScriptSegwit {
    DecodedScriptSegwit {
    }
  }

}



