/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// DecodedPsbtInputNonWitnessUtxo : Decoded network transaction for non-witness UTXOs

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct DecodedPsbtInputNonWitnessUtxo {
}

impl DecodedPsbtInputNonWitnessUtxo {
  /// Decoded network transaction for non-witness UTXOs
  pub fn new() -> DecodedPsbtInputNonWitnessUtxo {
    DecodedPsbtInputNonWitnessUtxo {
    }
  }

}



