/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsBitcoincliBlockVin3Prevout : Detailed previous output

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsBitcoincliBlockVin3Prevout {
}

impl GithubComSatstreamSsutilsBitcoincliBlockVin3Prevout {
  /// Detailed previous output
  pub fn new() -> GithubComSatstreamSsutilsBitcoincliBlockVin3Prevout {
    GithubComSatstreamSsutilsBitcoincliBlockVin3Prevout {
    }
  }

}



