/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsBitcoincliTxOutScriptPubKey : The public key script

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsBitcoincliTxOutScriptPubKey {
}

impl GithubComSatstreamSsutilsBitcoincliTxOutScriptPubKey {
  /// The public key script
  pub fn new() -> GithubComSatstreamSsutilsBitcoincliTxOutScriptPubKey {
    GithubComSatstreamSsutilsBitcoincliTxOutScriptPubKey {
    }
  }

}



