/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsBitcoincliPsbtWitnessUtxoScriptPubKey : The script pub key

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsBitcoincliPsbtWitnessUtxoScriptPubKey {
}

impl GithubComSatstreamSsutilsBitcoincliPsbtWitnessUtxoScriptPubKey {
  /// The script pub key
  pub fn new() -> GithubComSatstreamSsutilsBitcoincliPsbtWitnessUtxoScriptPubKey {
    GithubComSatstreamSsutilsBitcoincliPsbtWitnessUtxoScriptPubKey {
    }
  }

}



