/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsBitcoincliDecodedPsbtTx : The decoded network-serialized unsigned transaction

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsBitcoincliDecodedPsbtTx {
}

impl GithubComSatstreamSsutilsBitcoincliDecodedPsbtTx {
  /// The decoded network-serialized unsigned transaction
  pub fn new() -> GithubComSatstreamSsutilsBitcoincliDecodedPsbtTx {
    GithubComSatstreamSsutilsBitcoincliDecodedPsbtTx {
    }
  }

}



