/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsOrdServerResponsesRuneListEntry1 : The second element is the entry data

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsOrdServerResponsesRuneListEntry1 {
}

impl GithubComSatstreamSsutilsOrdServerResponsesRuneListEntry1 {
  /// The second element is the entry data
  pub fn new() -> GithubComSatstreamSsutilsOrdServerResponsesRuneListEntry1 {
    GithubComSatstreamSsutilsOrdServerResponsesRuneListEntry1 {
    }
  }

}



