/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsBitcoincliFeeHorizonEstimateFail : Information about highest range of feerates to fail

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsBitcoincliFeeHorizonEstimateFail {
}

impl GithubComSatstreamSsutilsBitcoincliFeeHorizonEstimateFail {
  /// Information about highest range of feerates to fail
  pub fn new() -> GithubComSatstreamSsutilsBitcoincliFeeHorizonEstimateFail {
    GithubComSatstreamSsutilsBitcoincliFeeHorizonEstimateFail {
    }
  }

}



