/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutInput {
  /// The transaction id
  #[serde(rename = "txid")]
  txid: Option<String>,
  /// The output number
  #[serde(rename = "vout")]
  vout: Option<i32>
}

impl GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutInput {
  pub fn new() -> GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutInput {
    GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutInput {
      txid: None,
      vout: None
    }
  }

  pub fn set_txid(&mut self, txid: String) {
    self.txid = Some(txid);
  }

  pub fn with_txid(mut self, txid: String) -> GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutInput {
    self.txid = Some(txid);
    self
  }

  pub fn txid(&self) -> Option<&String> {
    self.txid.as_ref()
  }

  pub fn reset_txid(&mut self) {
    self.txid = None;
  }

  pub fn set_vout(&mut self, vout: i32) {
    self.vout = Some(vout);
  }

  pub fn with_vout(mut self, vout: i32) -> GithubComSatstreamSsUtilsBitcoinCliTxSpendingPrevoutInput {
    self.vout = Some(vout);
    self
  }

  pub fn vout(&self) -> Option<&i32> {
    self.vout.as_ref()
  }

  pub fn reset_vout(&mut self) {
    self.vout = None;
  }

}



