/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsBitcoincliEstimateRawFeeMedium : Estimate for medium time horizon

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsBitcoincliEstimateRawFeeMedium {
}

impl GithubComSatstreamSsutilsBitcoincliEstimateRawFeeMedium {
  /// Estimate for medium time horizon
  pub fn new() -> GithubComSatstreamSsutilsBitcoincliEstimateRawFeeMedium {
    GithubComSatstreamSsutilsBitcoincliEstimateRawFeeMedium {
    }
  }

}



