/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsUtilsOrdServerResponsesOutput {
  #[serde(rename = "script_pubkey")]
  script_pubkey: Option<String>,
  #[serde(rename = "value")]
  value: Option<i32>
}

impl GithubComSatstreamSsUtilsOrdServerResponsesOutput {
  pub fn new() -> GithubComSatstreamSsUtilsOrdServerResponsesOutput {
    GithubComSatstreamSsUtilsOrdServerResponsesOutput {
      script_pubkey: None,
      value: None
    }
  }

  pub fn set_script_pubkey(&mut self, script_pubkey: String) {
    self.script_pubkey = Some(script_pubkey);
  }

  pub fn with_script_pubkey(mut self, script_pubkey: String) -> GithubComSatstreamSsUtilsOrdServerResponsesOutput {
    self.script_pubkey = Some(script_pubkey);
    self
  }

  pub fn script_pubkey(&self) -> Option<&String> {
    self.script_pubkey.as_ref()
  }

  pub fn reset_script_pubkey(&mut self) {
    self.script_pubkey = None;
  }

  pub fn set_value(&mut self, value: i32) {
    self.value = Some(value);
  }

  pub fn with_value(mut self, value: i32) -> GithubComSatstreamSsUtilsOrdServerResponsesOutput {
    self.value = Some(value);
    self
  }

  pub fn value(&self) -> Option<&i32> {
    self.value.as_ref()
  }

  pub fn reset_value(&mut self) {
    self.value = None;
  }

}



