/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsBitcoincliDecodedPsbtInputWitnessUtxo : Transaction output for witness UTXOs

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsBitcoincliDecodedPsbtInputWitnessUtxo {
}

impl GithubComSatstreamSsutilsBitcoincliDecodedPsbtInputWitnessUtxo {
  /// Transaction output for witness UTXOs
  pub fn new() -> GithubComSatstreamSsutilsBitcoincliDecodedPsbtInputWitnessUtxo {
    GithubComSatstreamSsutilsBitcoincliDecodedPsbtInputWitnessUtxo {
    }
  }

}



