/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsBitcoincliEstimateRawFeeLong : Estimate for long time horizon

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsBitcoincliEstimateRawFeeLong {
}

impl GithubComSatstreamSsutilsBitcoincliEstimateRawFeeLong {
  /// Estimate for long time horizon
  pub fn new() -> GithubComSatstreamSsutilsBitcoincliEstimateRawFeeLong {
    GithubComSatstreamSsutilsBitcoincliEstimateRawFeeLong {
    }
  }

}



