/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsBitcoincliDecodedPsbtInputRedeemScript : The redeem script

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsBitcoincliDecodedPsbtInputRedeemScript {
}

impl GithubComSatstreamSsutilsBitcoincliDecodedPsbtInputRedeemScript {
  /// The redeem script
  pub fn new() -> GithubComSatstreamSsutilsBitcoincliDecodedPsbtInputRedeemScript {
    GithubComSatstreamSsutilsBitcoincliDecodedPsbtInputRedeemScript {
    }
  }

}



