/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// GithubComSatstreamSsutilsBitcoincliFeeHorizonEstimatePass : Information about lowest range of feerates to succeed

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsutilsBitcoincliFeeHorizonEstimatePass {
}

impl GithubComSatstreamSsutilsBitcoincliFeeHorizonEstimatePass {
  /// Information about lowest range of feerates to succeed
  pub fn new() -> GithubComSatstreamSsutilsBitcoincliFeeHorizonEstimatePass {
    GithubComSatstreamSsutilsBitcoincliFeeHorizonEstimatePass {
    }
  }

}



