/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct GithubComSatstreamSsUtilsOrdServerResponsesDecodeResponse {
  #[serde(rename = "inscriptions")]
  inscriptions: Option<Vec<::models::GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription>>,
  #[serde(rename = "runestone")]
  runestone: Option<::models::GithubComSatstreamSsUtilsOrdServerResponsesRunestoneData>
}

impl GithubComSatstreamSsUtilsOrdServerResponsesDecodeResponse {
  pub fn new() -> GithubComSatstreamSsUtilsOrdServerResponsesDecodeResponse {
    GithubComSatstreamSsUtilsOrdServerResponsesDecodeResponse {
      inscriptions: None,
      runestone: None
    }
  }

  pub fn set_inscriptions(&mut self, inscriptions: Vec<::models::GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription>) {
    self.inscriptions = Some(inscriptions);
  }

  pub fn with_inscriptions(mut self, inscriptions: Vec<::models::GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription>) -> GithubComSatstreamSsUtilsOrdServerResponsesDecodeResponse {
    self.inscriptions = Some(inscriptions);
    self
  }

  pub fn inscriptions(&self) -> Option<&Vec<::models::GithubComSatstreamSsUtilsOrdServerResponsesDecodedInscription>> {
    self.inscriptions.as_ref()
  }

  pub fn reset_inscriptions(&mut self) {
    self.inscriptions = None;
  }

  pub fn set_runestone(&mut self, runestone: ::models::GithubComSatstreamSsUtilsOrdServerResponsesRunestoneData) {
    self.runestone = Some(runestone);
  }

  pub fn with_runestone(mut self, runestone: ::models::GithubComSatstreamSsUtilsOrdServerResponsesRunestoneData) -> GithubComSatstreamSsUtilsOrdServerResponsesDecodeResponse {
    self.runestone = Some(runestone);
    self
  }

  pub fn runestone(&self) -> Option<&::models::GithubComSatstreamSsUtilsOrdServerResponsesRunestoneData> {
    self.runestone.as_ref()
  }

  pub fn reset_runestone(&mut self) {
    self.runestone = None;
  }

}



