/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RawFeeEstimateShort : Estimate for short time horizon

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RawFeeEstimateShort {
}

impl RawFeeEstimateShort {
  /// Estimate for short time horizon
  pub fn new() -> RawFeeEstimateShort {
    RawFeeEstimateShort {
    }
  }

}



