/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RawMempoolData {
  /// Only if verbose is true
  #[serde(rename = "detailed")]
  detailed: Option<::std::collections::HashMap<String, ::models::MempoolEntry>>,
  #[serde(rename = "sequence")]
  sequence: Option<::models::RawMempoolDataSequence>,
  /// Only if verbose is false
  #[serde(rename = "txids")]
  txids: Option<Vec<String>>
}

impl RawMempoolData {
  pub fn new() -> RawMempoolData {
    RawMempoolData {
      detailed: None,
      sequence: None,
      txids: None
    }
  }

  pub fn set_detailed(&mut self, detailed: ::std::collections::HashMap<String, ::models::MempoolEntry>) {
    self.detailed = Some(detailed);
  }

  pub fn with_detailed(mut self, detailed: ::std::collections::HashMap<String, ::models::MempoolEntry>) -> RawMempoolData {
    self.detailed = Some(detailed);
    self
  }

  pub fn detailed(&self) -> Option<&::std::collections::HashMap<String, ::models::MempoolEntry>> {
    self.detailed.as_ref()
  }

  pub fn reset_detailed(&mut self) {
    self.detailed = None;
  }

  pub fn set_sequence(&mut self, sequence: ::models::RawMempoolDataSequence) {
    self.sequence = Some(sequence);
  }

  pub fn with_sequence(mut self, sequence: ::models::RawMempoolDataSequence) -> RawMempoolData {
    self.sequence = Some(sequence);
    self
  }

  pub fn sequence(&self) -> Option<&::models::RawMempoolDataSequence> {
    self.sequence.as_ref()
  }

  pub fn reset_sequence(&mut self) {
    self.sequence = None;
  }

  pub fn set_txids(&mut self, txids: Vec<String>) {
    self.txids = Some(txids);
  }

  pub fn with_txids(mut self, txids: Vec<String>) -> RawMempoolData {
    self.txids = Some(txids);
    self
  }

  pub fn txids(&self) -> Option<&Vec<String>> {
    self.txids.as_ref()
  }

  pub fn reset_txids(&mut self) {
    self.txids = None;
  }

}



