/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RawMempoolDataSequence : Only if mempool_sequence is true

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RawMempoolDataSequence {
}

impl RawMempoolDataSequence {
  /// Only if mempool_sequence is true
  pub fn new() -> RawMempoolDataSequence {
    RawMempoolDataSequence {
    }
  }

}



