/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RequestsDecodeScriptRequest {
  /// The hex-encoded script to decode
  #[serde(rename = "hexstring")]
  hexstring: String
}

impl RequestsDecodeScriptRequest {
  pub fn new(hexstring: String) -> RequestsDecodeScriptRequest {
    RequestsDecodeScriptRequest {
      hexstring: hexstring
    }
  }

  pub fn set_hexstring(&mut self, hexstring: String) {
    self.hexstring = hexstring;
  }

  pub fn with_hexstring(mut self, hexstring: String) -> RequestsDecodeScriptRequest {
    self.hexstring = hexstring;
    self
  }

  pub fn hexstring(&self) -> &String {
    &self.hexstring
  }


}



