/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RequestsCombineRawTransactionRequest {
  #[serde(rename = "hexstrings")]
  hexstrings: Vec<String>
}

impl RequestsCombineRawTransactionRequest {
  pub fn new(hexstrings: Vec<String>) -> RequestsCombineRawTransactionRequest {
    RequestsCombineRawTransactionRequest {
      hexstrings: hexstrings
    }
  }

  pub fn set_hexstrings(&mut self, hexstrings: Vec<String>) {
    self.hexstrings = hexstrings;
  }

  pub fn with_hexstrings(mut self, hexstrings: Vec<String>) -> RequestsCombineRawTransactionRequest {
    self.hexstrings = hexstrings;
    self
  }

  pub fn hexstrings(&self) -> &Vec<String> {
    &self.hexstrings
  }


}



