/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RequestsVerifyTxOutProofRequest {
  /// The hex-encoded proof generated by gettxoutproof
  #[serde(rename = "proof")]
  proof: Option<String>
}

impl RequestsVerifyTxOutProofRequest {
  pub fn new() -> RequestsVerifyTxOutProofRequest {
    RequestsVerifyTxOutProofRequest {
      proof: None
    }
  }

  pub fn set_proof(&mut self, proof: String) {
    self.proof = Some(proof);
  }

  pub fn with_proof(mut self, proof: String) -> RequestsVerifyTxOutProofRequest {
    self.proof = Some(proof);
    self
  }

  pub fn proof(&self) -> Option<&String> {
    self.proof.as_ref()
  }

  pub fn reset_proof(&mut self) {
    self.proof = None;
  }

}



