/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RequestsCreatePsbtRequest {
  /// The inputs for the transaction
  #[serde(rename = "inputs")]
  inputs: Vec<::models::RequestsCreatePsbtInput>,
  /// Raw locktime. Non-0 value also locktime-activates inputs
  #[serde(rename = "locktime")]
  locktime: Option<i32>,
  /// The outputs for the transaction (each address can only appear once)
  #[serde(rename = "outputs")]
  outputs: Vec<::models::RequestsCreatePsbtOutput>,
  /// Marks this transaction as BIP125-replaceable
  #[serde(rename = "replaceable")]
  replaceable: Option<bool>
}

impl RequestsCreatePsbtRequest {
  pub fn new(inputs: Vec<::models::RequestsCreatePsbtInput>, outputs: Vec<::models::RequestsCreatePsbtOutput>) -> RequestsCreatePsbtRequest {
    RequestsCreatePsbtRequest {
      inputs: inputs,
      locktime: None,
      outputs: outputs,
      replaceable: None
    }
  }

  pub fn set_inputs(&mut self, inputs: Vec<::models::RequestsCreatePsbtInput>) {
    self.inputs = inputs;
  }

  pub fn with_inputs(mut self, inputs: Vec<::models::RequestsCreatePsbtInput>) -> RequestsCreatePsbtRequest {
    self.inputs = inputs;
    self
  }

  pub fn inputs(&self) -> &Vec<::models::RequestsCreatePsbtInput> {
    &self.inputs
  }


  pub fn set_locktime(&mut self, locktime: i32) {
    self.locktime = Some(locktime);
  }

  pub fn with_locktime(mut self, locktime: i32) -> RequestsCreatePsbtRequest {
    self.locktime = Some(locktime);
    self
  }

  pub fn locktime(&self) -> Option<&i32> {
    self.locktime.as_ref()
  }

  pub fn reset_locktime(&mut self) {
    self.locktime = None;
  }

  pub fn set_outputs(&mut self, outputs: Vec<::models::RequestsCreatePsbtOutput>) {
    self.outputs = outputs;
  }

  pub fn with_outputs(mut self, outputs: Vec<::models::RequestsCreatePsbtOutput>) -> RequestsCreatePsbtRequest {
    self.outputs = outputs;
    self
  }

  pub fn outputs(&self) -> &Vec<::models::RequestsCreatePsbtOutput> {
    &self.outputs
  }


  pub fn set_replaceable(&mut self, replaceable: bool) {
    self.replaceable = Some(replaceable);
  }

  pub fn with_replaceable(mut self, replaceable: bool) -> RequestsCreatePsbtRequest {
    self.replaceable = Some(replaceable);
    self
  }

  pub fn replaceable(&self) -> Option<&bool> {
    self.replaceable.as_ref()
  }

  pub fn reset_replaceable(&mut self) {
    self.replaceable = None;
  }

}



