/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RequestsCombinePsbtRequest {
  /// Array of base64-encoded PSBTs to combine
  #[serde(rename = "psbts")]
  psbts: Vec<String>
}

impl RequestsCombinePsbtRequest {
  pub fn new(psbts: Vec<String>) -> RequestsCombinePsbtRequest {
    RequestsCombinePsbtRequest {
      psbts: psbts
    }
  }

  pub fn set_psbts(&mut self, psbts: Vec<String>) {
    self.psbts = psbts;
  }

  pub fn with_psbts(mut self, psbts: Vec<String>) -> RequestsCombinePsbtRequest {
    self.psbts = psbts;
    self
  }

  pub fn psbts(&self) -> &Vec<String> {
    &self.psbts
  }


}



