/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponsesGetTxOutResponseData : Transaction output details (null if not found)

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponsesGetTxOutResponseData {
}

impl ResponsesGetTxOutResponseData {
  /// Transaction output details (null if not found)
  pub fn new() -> ResponsesGetTxOutResponseData {
    ResponsesGetTxOutResponseData {
    }
  }

}



