/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponsesGetBlockStatsResponseData : Block statistics

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponsesGetBlockStatsResponseData {
}

impl ResponsesGetBlockStatsResponseData {
  /// Block statistics
  pub fn new() -> ResponsesGetBlockStatsResponseData {
    ResponsesGetBlockStatsResponseData {
    }
  }

}



