/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponsesEstimateSmartFeeResponseData : Smart fee estimation data

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponsesEstimateSmartFeeResponseData {
}

impl ResponsesEstimateSmartFeeResponseData {
  /// Smart fee estimation data
  pub fn new() -> ResponsesEstimateSmartFeeResponseData {
    ResponsesEstimateSmartFeeResponseData {
    }
  }

}



