/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponsesBlockRange {
  #[serde(rename = "end")]
  end: Option<i32>,
  #[serde(rename = "start")]
  start: Option<i32>
}

impl ResponsesBlockRange {
  pub fn new() -> ResponsesBlockRange {
    ResponsesBlockRange {
      end: None,
      start: None
    }
  }

  pub fn set_end(&mut self, end: i32) {
    self.end = Some(end);
  }

  pub fn with_end(mut self, end: i32) -> ResponsesBlockRange {
    self.end = Some(end);
    self
  }

  pub fn end(&self) -> Option<&i32> {
    self.end.as_ref()
  }

  pub fn reset_end(&mut self) {
    self.end = None;
  }

  pub fn set_start(&mut self, start: i32) {
    self.start = Some(start);
  }

  pub fn with_start(mut self, start: i32) -> ResponsesBlockRange {
    self.start = Some(start);
    self
  }

  pub fn start(&self) -> Option<&i32> {
    self.start.as_ref()
  }

  pub fn reset_start(&mut self) {
    self.start = None;
  }

}



