/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponsesSendRawTransactionData {
  #[serde(rename = "tx_hash")]
  tx_hash: Option<String>
}

impl ResponsesSendRawTransactionData {
  pub fn new() -> ResponsesSendRawTransactionData {
    ResponsesSendRawTransactionData {
      tx_hash: None
    }
  }

  pub fn set_tx_hash(&mut self, tx_hash: String) {
    self.tx_hash = Some(tx_hash);
  }

  pub fn with_tx_hash(mut self, tx_hash: String) -> ResponsesSendRawTransactionData {
    self.tx_hash = Some(tx_hash);
    self
  }

  pub fn tx_hash(&self) -> Option<&String> {
    self.tx_hash.as_ref()
  }

  pub fn reset_tx_hash(&mut self) {
    self.tx_hash = None;
  }

}



