/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponsesGetBlockchainInfoResponseData : Blockchain information

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponsesGetBlockchainInfoResponseData {
}

impl ResponsesGetBlockchainInfoResponseData {
  /// Blockchain information
  pub fn new() -> ResponsesGetBlockchainInfoResponseData {
    ResponsesGetBlockchainInfoResponseData {
    }
  }

}



