/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponsesDecodeScriptResponseData : Decoded script data

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponsesDecodeScriptResponseData {
}

impl ResponsesDecodeScriptResponseData {
  /// Decoded script data
  pub fn new() -> ResponsesDecodeScriptResponseData {
    ResponsesDecodeScriptResponseData {
    }
  }

}



