/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponsesEstimateRawFeeResponseData : Fee estimation data

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponsesEstimateRawFeeResponseData {
}

impl ResponsesEstimateRawFeeResponseData {
  /// Fee estimation data
  pub fn new() -> ResponsesEstimateRawFeeResponseData {
    ResponsesEstimateRawFeeResponseData {
    }
  }

}



