/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponsesValidateAddressResponseData : Address validation result

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponsesValidateAddressResponseData {
}

impl ResponsesValidateAddressResponseData {
  /// Address validation result
  pub fn new() -> ResponsesValidateAddressResponseData {
    ResponsesValidateAddressResponseData {
    }
  }

}



