/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ResponsesGetAddressTimeframeBalanceItemBlockRange : Time       time.Time  `json:\"time\"`

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ResponsesGetAddressTimeframeBalanceItemBlockRange {
}

impl ResponsesGetAddressTimeframeBalanceItemBlockRange {
  /// Time       time.Time  `json:\"time\"`
  pub fn new() -> ResponsesGetAddressTimeframeBalanceItemBlockRange {
    ResponsesGetAddressTimeframeBalanceItemBlockRange {
    }
  }

}



