/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RuneTerms {
  #[serde(rename = "amount")]
  amount: Option<i32>,
  #[serde(rename = "cap")]
  cap: Option<String>,
  #[serde(rename = "height")]
  height: Option<Vec<i32>>,
  #[serde(rename = "offset")]
  offset: Option<Vec<i32>>
}

impl RuneTerms {
  pub fn new() -> RuneTerms {
    RuneTerms {
      amount: None,
      cap: None,
      height: None,
      offset: None
    }
  }

  pub fn set_amount(&mut self, amount: i32) {
    self.amount = Some(amount);
  }

  pub fn with_amount(mut self, amount: i32) -> RuneTerms {
    self.amount = Some(amount);
    self
  }

  pub fn amount(&self) -> Option<&i32> {
    self.amount.as_ref()
  }

  pub fn reset_amount(&mut self) {
    self.amount = None;
  }

  pub fn set_cap(&mut self, cap: String) {
    self.cap = Some(cap);
  }

  pub fn with_cap(mut self, cap: String) -> RuneTerms {
    self.cap = Some(cap);
    self
  }

  pub fn cap(&self) -> Option<&String> {
    self.cap.as_ref()
  }

  pub fn reset_cap(&mut self) {
    self.cap = None;
  }

  pub fn set_height(&mut self, height: Vec<i32>) {
    self.height = Some(height);
  }

  pub fn with_height(mut self, height: Vec<i32>) -> RuneTerms {
    self.height = Some(height);
    self
  }

  pub fn height(&self) -> Option<&Vec<i32>> {
    self.height.as_ref()
  }

  pub fn reset_height(&mut self) {
    self.height = None;
  }

  pub fn set_offset(&mut self, offset: Vec<i32>) {
    self.offset = Some(offset);
  }

  pub fn with_offset(mut self, offset: Vec<i32>) -> RuneTerms {
    self.offset = Some(offset);
    self
  }

  pub fn offset(&self) -> Option<&Vec<i32>> {
    self.offset.as_ref()
  }

  pub fn reset_offset(&mut self) {
    self.offset = None;
  }

}



