/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RunesListResponse {
  #[serde(rename = "entries")]
  entries: Option<Vec<::models::RuneListEntry>>,
  #[serde(rename = "more")]
  more: Option<bool>,
  #[serde(rename = "next")]
  next: Option<i32>,
  #[serde(rename = "prev")]
  prev: Option<i32>
}

impl RunesListResponse {
  pub fn new() -> RunesListResponse {
    RunesListResponse {
      entries: None,
      more: None,
      next: None,
      prev: None
    }
  }

  pub fn set_entries(&mut self, entries: Vec<::models::RuneListEntry>) {
    self.entries = Some(entries);
  }

  pub fn with_entries(mut self, entries: Vec<::models::RuneListEntry>) -> RunesListResponse {
    self.entries = Some(entries);
    self
  }

  pub fn entries(&self) -> Option<&Vec<::models::RuneListEntry>> {
    self.entries.as_ref()
  }

  pub fn reset_entries(&mut self) {
    self.entries = None;
  }

  pub fn set_more(&mut self, more: bool) {
    self.more = Some(more);
  }

  pub fn with_more(mut self, more: bool) -> RunesListResponse {
    self.more = Some(more);
    self
  }

  pub fn more(&self) -> Option<&bool> {
    self.more.as_ref()
  }

  pub fn reset_more(&mut self) {
    self.more = None;
  }

  pub fn set_next(&mut self, next: i32) {
    self.next = Some(next);
  }

  pub fn with_next(mut self, next: i32) -> RunesListResponse {
    self.next = Some(next);
    self
  }

  pub fn next(&self) -> Option<&i32> {
    self.next.as_ref()
  }

  pub fn reset_next(&mut self) {
    self.next = None;
  }

  pub fn set_prev(&mut self, prev: i32) {
    self.prev = Some(prev);
  }

  pub fn with_prev(mut self, prev: i32) -> RunesListResponse {
    self.prev = Some(prev);
    self
  }

  pub fn prev(&self) -> Option<&i32> {
    self.prev.as_ref()
  }

  pub fn reset_prev(&mut self) {
    self.prev = None;
  }

}



