/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// RuneListEntry1 : The second element is the entry data

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct RuneListEntry1 {
}

impl RuneListEntry1 {
  /// The second element is the entry data
  pub fn new() -> RuneListEntry1 {
    RuneListEntry1 {
    }
  }

}



