/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// UtxoBlockInfoUnspendables : Detailed view of unspendable categories

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct UtxoBlockInfoUnspendables {
}

impl UtxoBlockInfoUnspendables {
  /// Detailed view of unspendable categories
  pub fn new() -> UtxoBlockInfoUnspendables {
    UtxoBlockInfoUnspendables {
    }
  }

}



