/* 
 * Satstream API
 *
 * Satstream API
 *
 * OpenAPI spec version: 1.0
 * Contact: team@satstream.io
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct Vout {
  #[serde(rename = "n")]
  n: Option<i32>,
  #[serde(rename = "scriptPubKey")]
  script_pub_key: Option<::models::ScriptPubKey>,
  #[serde(rename = "value")]
  value: Option<f32>
}

impl Vout {
  pub fn new() -> Vout {
    Vout {
      n: None,
      script_pub_key: None,
      value: None
    }
  }

  pub fn set_n(&mut self, n: i32) {
    self.n = Some(n);
  }

  pub fn with_n(mut self, n: i32) -> Vout {
    self.n = Some(n);
    self
  }

  pub fn n(&self) -> Option<&i32> {
    self.n.as_ref()
  }

  pub fn reset_n(&mut self) {
    self.n = None;
  }

  pub fn set_script_pub_key(&mut self, script_pub_key: ::models::ScriptPubKey) {
    self.script_pub_key = Some(script_pub_key);
  }

  pub fn with_script_pub_key(mut self, script_pub_key: ::models::ScriptPubKey) -> Vout {
    self.script_pub_key = Some(script_pub_key);
    self
  }

  pub fn script_pub_key(&self) -> Option<&::models::ScriptPubKey> {
    self.script_pub_key.as_ref()
  }

  pub fn reset_script_pub_key(&mut self) {
    self.script_pub_key = None;
  }

  pub fn set_value(&mut self, value: f32) {
    self.value = Some(value);
  }

  pub fn with_value(mut self, value: f32) -> Vout {
    self.value = Some(value);
    self
  }

  pub fn value(&self) -> Option<&f32> {
    self.value.as_ref()
  }

  pub fn reset_value(&mut self) {
    self.value = None;
  }

}



